eureka:
  client:
    service-url:
      defaultZone: ${common.address}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true