services:
  config-server:
    build:
      context: .
      dockerfile: ./config-server/docker/Dockerfile
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app-network

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/docker/Dockerfile
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - app-network

  gateway-service:
    build:
      context: .
      dockerfile: ./gateway-service/docker/Dockerfile
    image: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network

  account-service:
    build:
      context: .
      dockerfile: ./account-service/docker/Dockerfile
    image: account-service
    container_name: account-service
    ports:
      - "8081:8081"
    depends_on:
      - gateway-service
    networks:
      - app-network

  authentication-service:
    build:
      context: .
      dockerfile: ./authentication-service/docker/Dockerfile
    image: authentication-service
    container_name: authentication-service
    ports:
      - "8082:8082"
    depends_on:
      - gateway-service
    networks:
      - app-network

  position-service:
    build:
      context: .
      dockerfile: ./position-service/docker/Dockerfile
    image: position-service
    container_name: position-service
    ports:
      - "8083:8083"
    depends_on:
      - gateway-service
    networks:
      - app-network

  department-service:
    build:
      context: .
      dockerfile: ./department-service/docker/Dockerfile
    image: department-service
    container_name: department-service
    ports:
      - "8084:8084"
    depends_on:
      - gateway-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
