networks:
  app-network:
    name: app-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "app-network"

services:
  config-server:
    build:
      context: .
      dockerfile: ./config-server/docker/Dockerfile
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app-network

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/docker/Dockerfile
    image: eureka-server
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - app-network
    entrypoint: ["sh", "-c", "until curl -s http://config-server:8888/actuator/health; do echo 'Waiting for Config Server...'; sleep 5; done; java -jar /app.jar"]

  api-gateway:
    build:
      context: .
      dockerfile: ./gateway-service/docker/Dockerfile
    image: api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=server
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - app-network
    entrypoint: ["sh", "-c", "until curl -s http://eureka-server:8761/eureka/apps; do echo 'Waiting for Eureka...'; sleep 5; done; java -jar /app.jar"]

  account-service:
    build:
      context: .
      dockerfile: ./account-service/docker/Dockerfile
    image: account-service
    container_name: account-service
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway
    networks:
      - app-network
    entrypoint: ["sh", "-c", "until curl -s http://api-gateway:8080/actuator/health; do echo 'Waiting for API Gateway...'; sleep 5; done; java -jar /app.jar"]
#
#  authentication-service:
#    build:
#      context: .
#      dockerfile: ./authentication-service/docker/Dockerfile
#    image: authentication-service
#    container_name: authentication-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - api-gateway
#    networks:
#      - app-network
#    entrypoint: ["sh", "-c", "until curl -s http://api-gateway:8080/actuator/health; do echo 'Waiting for API Gateway...'; sleep 5; done; java -jar /app.jar"]
#
#  position-service:
#    build:
#      context: .
#      dockerfile: ./position-service/docker/Dockerfile
#    image: position-service
#    container_name: position-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - api-gateway
#    networks:
#      - app-network
#    entrypoint: ["sh", "-c", "until curl -s http://api-gateway:8080/actuator/health; do echo 'Waiting for API Gateway...'; sleep 5; done; java -jar /app.jar"]
#
#  department-service:
#    build:
#      context: .
#      dockerfile: ./department-service/docker/Dockerfile
#    image: department-service
#    container_name: department-service
#    ports:
#      - "8084:8084"
#    depends_on:
#      - api-gateway
#    networks:
#      - app-network
#    entrypoint: ["sh", "-c", "until curl -s http://api-gateway:8080/actuator/health; do echo 'Waiting for API Gateway...'; sleep 5; done; java -jar /app.jar"]
