server:
  port: 8084

spring:
  application:
    name: department-service

swagger:
  packages-to-scan: vti.department-service

openapi:
  service:
    server: ${common.address}:${server.port}

logging:
  level:
    vti.accountservice: DEBUG
    org.springframework: INFO


