eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.99:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: api-gateway
    prefer-ip-address: true