spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      enabled: false
  config:
    import-check:
      enabled: false

spring.config.import: optional:classpath:common-application.properties

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8080
