server:
  port: 8080

openapi:
  service:
    server: ${common.address}:${server.port}

swagger:
  packages-to-scan: vti.gatewayservice

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  config:
    import: optional:classpath:common-application.properties
  profiles:
    active: local
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
