#spring.application.name=gateway-service
#spring.cloud.config.enabled=false
#spring.config.import=optional:classpath:common-application-local.properties

#server.port=8080
#openapi.service.server=${common.address}:${server.port}
#swagger.packages-to-scan=vti.gatewayservice
#
#
##tu dong kham pha de su dung dich vu eureka
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#spring.cloud.gateway.discovery.locator.enabled=true
#eureka.client.service-url.defaultZone=${common.address}:8761/eureka/
#spring.cloud.discovery.enabled=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#
## Spring Cloud Gateway routes configuration
#spring.cloud.gateway.routes[0].id=account-service
#spring.cloud.gateway.routes[0].uri=lb://account-service
#spring.cloud.gateway.routes[0].predicates=Path=/api/account/**
#
#spring.cloud.gateway.routes[1].id=authentication-service
#spring.cloud.gateway.routes[1].uri=lb://authentication-service
#spring.cloud.gateway.routes[1].predicates=Path=/api/auth/**
#
#spring.cloud.gateway.routes[2].id=position-service
#spring.cloud.gateway.routes[2].uri=lb://position-service
#spring.cloud.gateway.routes[2].predicates=Path=/api/position/**
#
#spring.cloud.gateway.routes[3].id=department-service
#spring.cloud.gateway.routes[3].uri=lb://department-service
#spring.cloud.gateway.routes[3].predicates=Path=/api/department/**
#
## Spring Actuator configuration
#management.endpoints.web.exposure.include=health,info
#
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#spring.main.web-application-type=reactive