spring:
  application:
    name: authentication-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8082

swagger:
  packages-to-scan: vti.authenticationservice

openapi:
  service:
    server: ${common.address}:${server.port}
