server:
  port: 8081

spring:
  application:
    name: account-service

swagger:
  packages-to-scan: vti.account-service

openapi:
  service:
    server: ${common.address}:${server.port}

logging:
  level:
    vti.accountservice: DEBUG
    org.springframework: INFO


keycloak:
  realm: testing-system
  auth-server-url: http://192.168.1.99:8000
  admin-client-id: microservice-client
  admin-client-secret: 1EECqTgOC8PkuudEKz0K6eK4pg5JoRIT