pipeline {
    agent any

    parameters {
        booleanParam(name: 'RUN_SONAR', defaultValue: true, description: '✅ Bật Sonar + Jacoco phân tích mã nguồn?')
    }

    environment {
        IMAGE_TAG = 'latest'
        DOCKER_HUB_USER = 'karobest10'
        SERVICE_NAME = 'account-service'
    }

    tools {
        maven 'maven_3.9'
        jdk 'JDK 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/kiennt94/microservice'
            }
        }

        stage('SonarQube Analysis') {
            when {
                expression { params.RUN_SONAR }
            }
            steps {
                withSonarQubeEnv('SonarQube') {
                    withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                        sh '''#!/bin/bash
                            mvn clean verify \
                                -pl ${SERVICE_NAME} -am \
                                -DskipTests=false \
                                -Dsonar.projectKey=${SERVICE_NAME} \
                                -Dsonar.projectName=${SERVICE_NAME} \
                                -Dsonar.host.url=http://sonarqube:9000 \
                                -Dsonar.token=$SONAR_TOKEN \
                                sonar:sonar
                        '''
                    }
                }
            }
        }

        stage('Unit Test') {
            steps {
                sh "mvn test -pl ${SERVICE_NAME} -am"
            }
        }

        stage('Build Maven Module') {
             steps {
                 sh "mvn clean install -pl ${SERVICE_NAME} -am"
             }
         }

         stage('Build Docker Image') {
             steps {
                 dir("${SERVICE_NAME}") {
                     sh "docker build -t ${SERVICE_NAME}:${IMAGE_TAG} -f docker/Dockerfile ."
                     sh "docker tag ${SERVICE_NAME}:${IMAGE_TAG} ${DOCKER_HUB_USER}/mrs-${SERVICE_NAME}:${IMAGE_TAG}"
                 }
             }
         }

      stage('Push Docker Image') {
          steps {
              withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                  sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                  sh "docker push ${DOCKER_HUB_USER}/mrs-${SERVICE_NAME}:${IMAGE_TAG}"
              }
          }
      }

      stage('Deploy Container') {
          steps {
              sh "docker rm -f ${SERVICE_NAME} || true"
              sh "docker run -d --network app-network --name ${SERVICE_NAME} ${DOCKER_HUB_USER}/mrs-${SERVICE_NAME}:${IMAGE_TAG}"
          }
      }
    }

    post {
        success {
            echo "✅ Build + Deploy thành công: ${SERVICE_NAME}"
        }
        failure {
            echo "❌ Có lỗi xảy ra khi build hoặc deploy: ${SERVICE_NAME}"
        }
    }
}
