pipeline {
    agent any

    parameters {
        string(name: 'SERVICE_NAME', defaultValue: 'account-service', description: 'Tên service cần build (VD: account-service)')
    }

    environment {
        IMAGE_TAG = 'latest'
        DOCKER_HUB_USER = 'karobest10'
    }

    tools {
        maven 'maven_3.9'
        jdk 'JDK 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/kiennt94/microservice'
            }
        }

        stage('Build Maven Module') {
            steps {
                sh "mvn clean install -pl ${params.SERVICE_NAME} -am -DskipTests"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${params.SERVICE_NAME}:${IMAGE_TAG} -f ${params.SERVICE_NAME}/docker/Dockerfile ${params.SERVICE_NAME}"
                sh "docker tag ${params.SERVICE_NAME}:${IMAGE_TAG} ${DOCKER_HUB_USER}/mrs-${params.SERVICE_NAME}:${IMAGE_TAG}"
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${DOCKER_HUB_USER}/mrs-${params.SERVICE_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh "docker rm -f ${params.SERVICE_NAME} || true"
                sh "docker run -d --network app-network --name ${params.SERVICE_NAME} ${DOCKER_HUB_USER}/mrs-${params.SERVICE_NAME}:${IMAGE_TAG}"
            }
        }
    }

    post {
        success {
            echo "✅ Build + Deploy thành công: ${params.SERVICE_NAME}"
        }
        failure {
            echo "❌ Có lỗi xảy ra khi build: ${params.SERVICE_NAME}"
        }
    }
}
